branches:
  - "+([0-9])?(.{+([0-9]),x}).x"
  - master
  - next
  - name: beta
    prerelease: true
  - name: alpha
    prerelease: true
plugins:
  - "@semantic-release/commit-analyzer"
  - - "@semantic-release/exec"
    - prepareCmd: '
        yq e ''.version = "${nextRelease.version}"'' -i ./Chart.yaml
        '
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
        - ./Chart.yaml
      message: |
        chore(release): version ${nextRelease.version}
        \n
        \n
        ${nextRelease.notes}


