{{- define "common.app-env-configmap" -}}
{{- $indexValues := index .Values "helm-common" -}}
{{- $common := dict "Values" $indexValues -}}
{{- $noCommon := omit .Values "helm-common" -}}
{{- $overrides := dict "Values" $noCommon -}}
{{- $noValues := omit . "Values" -}}
{{- with mergeOverwrite $noValues $common $overrides -}}
{{- if .Values.env -}}
{{- if .Values.env.configMap -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appEnvConfigMap.name }}
  {{- if .Values.appEnvConfigMap.annotations }}
  annotations:
    {{- range $key, $val := .Values.appEnvConfigMap.annotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
  {{- end }}
data:
  {{- range $key, $val := .Values.env.configMap }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
