{{- define "common.cronjob" -}}
{{- $indexValues := index .Values "helm-common" -}}
{{- $common := dict "Values" $indexValues -}}
{{- $noCommon := omit .Values "helm-common" -}}
{{- $overrides := dict "Values" $noCommon -}}
{{- $noValues := omit . "Values" -}}
{{- with mergeOverwrite $noValues $common $overrides -}}
{{- if semverCompare ">=1.21-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: batch/v1
{{- else -}}
apiVersion: batch/v1beta1
{{- end }}
kind: CronJob
{{ include "common.metadata" . }}
spec:
  concurrencyPolicy: {{ .Values.cronJob.concurrencyPolicy }}
  failedJobsHistoryLimit: {{ .Values.cronJob.failedJobsHistoryLimit }}
  startingDeadlineSeconds: {{ .Values.cronJob.startingDeadlineSeconds }}
  successfulJobsHistoryLimit: {{ .Values.cronJob.successfulJobsHistoryLimit }}
  schedule: {{ .Values.cronJob.schedule | quote}}
  suspend: {{ .Values.cronJob.suspend }}
  jobTemplate:
    spec:
      activeDeadlineSeconds: {{ .Values.cronJob.job.activeDeadlineSeconds }}
      backoffLimit: {{ .Values.cronJob.job.backoffLimit }}
      completions: {{ .Values.cronJob.job.completions }}
      parallelism: {{ .Values.cronJob.job.parallelism }}
      ttlSecondsAfterFinished: {{ .Values.cronJob.job.ttlSecondsAfterFinished }}
      template:
        metadata:
          annotations: {{- include "common.podAnnotations" . | nindent 12 }}
        spec: {{- include "common.podSpec.mainPart" . | nindent 10 }}
          restartPolicy: {{ .Values.cronJob.job.podRestartPolicy }}
          {{- include "common.podSpec.selectorsTolerationsAffinity" . | nindent 10 }}
{{- end -}}
{{- end -}}