{{- define "common.service" -}}
{{- $indexValues := index .Values "helm-common" -}}
{{- $common := dict "Values" $indexValues -}}
{{- $noCommon := omit .Values "helm-common" -}}
{{- $overrides := dict "Values" $noCommon -}}
{{- $noValues := omit . "Values" -}}
{{- with mergeOverwrite $noValues $common $overrides -}}
apiVersion: v1
kind: Service
{{ include "common.metadata" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "helm-common.selectorLabels" . | nindent 4 }}
{{- end -}}
{{- end -}}
