{{- define "common.deployment" -}}
{{- $indexValues := index .Values "helm-common" -}}
{{- $common := dict "Values" $indexValues -}}
{{- $noCommon := omit .Values "helm-common" -}}
{{- $overrides := dict "Values" $noCommon -}}
{{- $noValues := omit . "Values" -}}
{{- with mergeOverwrite $noValues $common $overrides -}}
apiVersion: apps/v1
kind: Deployment
{{ include "common.metadata" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    {{- $valid := list "RollingUpdate" "Recreate" }}
    {{- if not (has .Values.deployment.strategy.type $valid) }}
    {{- fail "Invalid strategy type, must be one of (RollingUpdate,Recreate)" }}
    {{- end }}
    type: {{ .Values.deployment.strategy.type }}
    {{- if eq .Values.deployment.strategy.type "RollingUpdate" }}
    rollingUpdate:
      maxUnavailable: {{ .Values.deployment.strategy.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.deployment.strategy.rollingUpdate.maxSurge }}
    {{- end }}
  progressDeadlineSeconds: {{ .Values.deployment.progressDeadlineSeconds }}
  minReadySeconds: {{ .Values.deployment.minReadySeconds }}
  revisionHistoryLimit: {{ .Values.deployment.revisionHistoryLimit }}
  paused: {{ .Values.deployment.paused }}
  selector:
    matchLabels: {{- include "helm-common.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations: {{- include "common.podAnnotations" . | nindent 8 }}
      labels: {{- include "helm-common.selectorLabels" . | nindent 8 }}
    spec: {{- include "common.podSpec.mainPart" . | nindent 6 }}
        {{- include "common.podSpec.containerPortsAndProbes" . | nindent 8 }}
      {{- include "common.podSpec.selectorsTolerationsAffinity" . | nindent 6 }}
{{- end -}}
{{- end -}}
