{{- define "common.ingress" -}}
{{- $indexValues := index .Values "helm-common" -}}
{{- $common := dict "Values" $indexValues -}}
{{- $noCommon := omit .Values "helm-common" -}}
{{- $overrides := dict "Values" $noCommon -}}
{{- $noValues := omit . "Values" -}}
{{- with mergeOverwrite $noValues $common $overrides -}}
{{- if .Values.ingress.enabled -}}
{{- $fullName := include "helm-common.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "helm-common.labels" . | nindent 4 }}
  annotations:
    {{- if semverCompare "<1.19-0" .Capabilities.KubeVersion.GitVersion }}
    kubernetes.io/ingress.class: {{ tpl ( .Values.ingress.ingressClass | quote ) . }}
    {{- end }}
    {{- if .Values.ingress.annotations }}
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
    {{- end }}
spec:
  {{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
  ingressClassName: {{ tpl ( .Values.ingress.ingressClass | quote ) . }}
  {{- end }}
  tls:
    - hosts:
        {{- range .Values.ingress.hosts }}
        - {{ tpl . $}}
        {{- end }}
  rules:
    {{- $paths := .Values.ingress.paths }}
    {{- range .Values.ingress.hosts }}
    - host: {{ tpl . $}}
      http:
        paths:
          {{- range $paths }}
          {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
          - path: {{ .path }}
            pathType: Prefix
            backend:
              service:
                name: {{ tpl .backend.serviceName $}}
                port:
                  number: {{ default $svcPort .backend.servicePort }}
          {{- else }}
          - path: {{ .path }}
            backend:
              serviceName: {{ tpl .backend.serviceName $}}
              servicePort: {{ default $svcPort .backend.servicePort }}
          {{- end }}
          {{- end }}
    {{- end }}
{{- end }}
{{- end -}}
{{- end -}}
